<a href="https://colab.research.google.com/github/aksl007/ai_source/blob/main/1_01_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

n차원 넘파이 배열

In [ ]:
import numpy as np

# 1D 배열 (Rank 1)
array_1d = np.array([1, 2, 3, 4])
print(array_1d)
print("1D 배열의 차원 (Rank):", array_1d.ndim) # 출력: 1

# 2D 배열 (Rank 2)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
print("2D 배열의 차원 (Rank):", array_2d.ndim) # 출력: 2

# 3D 배열 (Rank 3)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array_3d)
print("3D 배열의 차원 (Rank):", array_3d.ndim) # 출력: 3


[1 2 3 4]
1D 배열의 차원 (Rank): 1
[[1 2 3]
 [4 5 6]]
2D 배열의 차원 (Rank): 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3D 배열의 차원 (Rank): 3


arrary - 요소별 곱셈

In [ ]:
# array_2d = np.array([[1, 2, 3], [4, 5, 6]])
# print(array_2d)


array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])
result = array_1 * array_2
print(result)


[[ 5 12]
 [21 32]]


matrix - 행렬곱셈

In [ ]:
# import numpy as np

# matrix = np.matrix([[1, 2, 3], [4, 5, 6]])
# print(matrix)

matrix_1 = np.matrix([[1, 2], [3, 4]])
matrix_2 = np.matrix([[5, 6], [7, 8]])
result = matrix_1 * matrix_2
print(result)



[[19 22]
 [43 50]]


arrange 함수

In [ ]:
import numpy as np

# 0부터 10까지 1씩 증가하는 1차원 배열 생성
array1 = np.arange(0, 10, 1)
print("NumPy arange example (0 to 10):", array1)

# 0부터 10까지 2씩 증가
array2 = np.arange(0, 10, 2)
print("NumPy arange example (0 to 10 with step 2):", array2)

# 0부터 1까지 0.2씩 증가하는 실수 배열 생성
array3 = np.arange(0, 1, 0.2)
print("NumPy arange example (0 to 1 with step 0.2):", array3)

NumPy arange example (0 to 10): [0 1 2 3 4 5 6 7 8 9]
NumPy arange example (0 to 10 with step 2): [0 2 4 6 8]
NumPy arange example (0 to 1 with step 0.2): [0.  0.2 0.4 0.6 0.8]


Python range 함수

In [ ]:
# 0부터 10까지 1씩 증가하는 정수 시퀀스 생성
range1 = range(0, 10, 1)
print("Python range example (0 to 10):", list(range1))

# 0부터 10까지 2씩 증가하는 정수 시퀀스 생성
range2 = range(0, 10, 2)
print("Python range example (0 to 10 with step 2):", list(range2))


Python range example (0 to 10): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Python range example (0 to 10 with step 2): [0, 2, 4, 6, 8]


2D NumPy 배열 생성

In [ ]:
import numpy as np

# 2D NumPy 배열 생성
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D NumPy Array:")
print(array_2d)

# 배열의 모양(행과 열의 수) 확인
shape = array_2d.shape
print("\nArray Shape:", shape)

# 행의 수와 열의 수를 각각 출력
rows = shape[0]
columns = shape[1]
print("Number of Rows:", rows)
print("Number of Columns:", columns)


2D NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array Shape: (3, 3)
Number of Rows: 3
Number of Columns: 3


flatten

In [ ]:
import numpy as np

# 2D 배열 생성
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 배열을 1D로 평탄화
flattened_array = array_2d.flatten()


print("Original 2D Array:")
print(array_2d)
print("\nFlattened 1D Array:")
print(flattened_array)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flattened 1D Array:
[1 2 3 4 5 6]


indexing

In [ ]:
import numpy as np

# 1D 배열
array_1d = np.array([10, 20, 30, 40, 50])
print("1D 배열에서 3번째 요소:", array_1d[2])  # 출력: 30

# 2D 배열
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D 배열에서 (2, 3) 요소:", array_2d[1, 2])  # 출력: 6


1D 배열에서 3번째 요소: 30
2D 배열에서 (2, 3) 요소: 6


In [ ]:
array_2d[1,2] = 60
print(array_2d[1,2])

60


Slicing

In [ ]:
import numpy as np

# 1D 배열
array_1d = np.array([10, 20, 30, 40, 50])
print("1D 배열에서 2번째 요소부터 4번째 요소까지:", array_1d[1:4]) # 출력: [20 30 40]

array_1d[1:4] = [40, 30, 20]
print(array_1d[1:4])

# 2D 배열
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D 배열에서 2번째 행부터 끝까지, 2번째 열만 선택:")
print(array_2d[1:, 1])   # 출력: [5 8]

# 2D 배열에서 특정 영역 추출
print("2D 배열에서 1~2번째 행, 2~3번째 열:")
print(array_2d[0:2, 1:3]) # 출력: [[2 3]
                          #       [5 6]]

1D 배열에서 2번째 요소부터 4번째 요소까지: [20 30 40]
[40 30 20]
2D 배열에서 2번째 행부터 끝까지, 2번째 열만 선택:
[5 8]
2D 배열에서 1~2번째 행, 2~3번째 열:
[[2 3]
 [5 6]]


Conditional **Filtering**

In [ ]:
import numpy as np

# 1D NumPy 배열 생성
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# 조건 필터링: 5보다 큰 요소 선택
condition = array > 5
filtered_array = array[array > 5]

print("5보다 큰 값:", filtered_array)
print(condition)


5보다 큰 값: [6 7 8 9]
[False False False False False  True  True  True  True]


In [ ]:
import numpy as np

# 2D NumPy 배열 생성
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 조건 필터링: 배열에서 짝수 요소들만 선택
condition = array_2d % 2 == 0
filtered_array_2d = array_2d[condition]
print("조건에 맞는 요소들 (짝수):", filtered_array_2d)


조건에 맞는 요소들 (짝수): [2 4 6 8]


In [ ]:
# 다중 조건 필터링
import numpy as np

# 1D NumPy 배열 생성
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 조건 필터링: 배열에서 3보다 크고 8보다 작은 요소들만 선택
condition = (array > 3) & (array < 8)
filtered_array = array[condition]
print("조건에 맞는 요소들 (3보다 크고 8보다 작은):", filtered_array)

조건에 맞는 요소들 (3보다 크고 8보다 작은): [4 5 6 7]


In [ ]:
import numpy as np

array1 = np.array([[2, 2], [2, 2]])
array2 = np.arange(4).reshape(2, 2)

print(array1)

print(array2)

mul = array1 * array2

print(mul.flatten())

[[2 2]
 [2 2]]
[[0 1]
 [2 3]]
[0 2 4 6]
